version: "3.9"

services:
  mysql:
    image: mysql:latest
    container_name: mysql
    restart: always
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: 1234
      MYSQL_DATABASE: HelloWorld
      MYSQL_USER: bob  # Create a user (optional)
      MYSQL_PASSWORD: 101  # Set a password for the user (optional)
# No volumes defined
